name: adisyon_uygulamasi
description: Supabase tabanlı yeni nesil adisyon uygulaması.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase ile iletişim için temel paket
  supabase_flutter: ^2.5.0
  # Tarih/saat formatlama için
  intl: ^0.19.0
  fl_chart: ^0.68.0
  # Özel yazı tipleri için
  google_fonts: ^6.1.0
  # Nesne karşılaştırma ve hash kodları için
  equatable: ^2.0.5
  provider: ^6.0.5

  cupertino_icons: ^1.0.2
  animations: ^2.0.11
  ffi: ^2.0.1
  audioplayers: 6.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - assets/sounds/order_confirmed.mp3
    - assets/sounds/order_ready.mp3
    - assets/sounds/order_received.mp3
    - assets/sounds/service_completed.mp3
    - assets/sounds/payment_received.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "logo.png" 