name: adisyon_uygulamasi
description: Supabase tabanlı yeni nesil adisyon uygulaması.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase ile iletişim için temel paket
  supabase_flutter: ^2.5.0
  # Tarih/saat formatlama için
  intl: ^0.19.0
  fl_chart: ^0.68.0
  # Özel yazı tipleri için
  google_fonts: ^6.1.0
  # Nesne karşılaştırma ve hash kodları için
  equatable: ^2.0.5

  cupertino_icons: ^1.0.2
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 